version: '3.8'
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x-draw
    ports:
      - "5432:5432"

  http-backend:
    build:
      context: ./
      dockerfile: ./docker/Docker.http
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/x-draw
      - JWT_SECRET=slfsfkfkdhfyureyurehdsjch37837u9fd78d7f8d7d8f
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  ws-backend:
    build:
      context: ./
      dockerfile: ./docker/Docker.ws 
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=slfsfkfkdhfyureyurehdsjch37837u9fd78d7f8d7d8f
    ports:
      - "8080:8080"
    depends_on:
      - redis
 
  db-migrator:
    build:
      context: ./
      dockerfile: ./docker/Docker.db
      args:
        DATABASE_URL: postgresql://postgres:postgres@postgres:5432/x-draw
    depends_on:
      postgres:
          condition: service_healthy

  worker:
    build:
      context: ./
      dockerfile: ./docker/Docker.worker
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/x-draw
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./
      dockerfile: ./docker/Docker.frontend
    environment: 
      - NEXT_PUBLIC_HTTP_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - worker
      - ws-backend
      - http-backend

volumes:
  postgres-data:
